spring.application.name=perfiles-service
server.port=8080

# Mongo
spring.data.mongodb.uri=${MONGO_URI}
# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

# spring.main.allow-bean-definition-overriding=true

# nombres
# rabbitmq.exchange=empleados-exchange
# rabbitmq.queue.perfiles=perfiles-queue
# rabbitmq.routingkey.creado=empleado.creado